openshift_cluster_content:
- object: projectrequest
  content:
  - name: "myapp-space2-quota"
    file: "{{ inventory_dir }}/../files/quota-medium.yml"
    namespace: "myapp-space2-quota"
  - name: "myapp-space4"
    file: "{{ inventory_dir }}/../files/quota-large.yml"
    namespace: "myapp-space4"
