---
 
 - name: Resize image and create openshift custom login page with the image.
   hosts: masters
   gather_facts: false

   roles:
     - { role: Jooho.image-resize, input_img: "{{logo_img_file}}", output_img: "{{output_img_file}}", overwrite_force: true ,when: "inventory_hostname == groups.masters[0]" }
     - { role: Jooho.openshift-custom-login-page, logo_img: "{{output_img_file}}", master_url: "master1.example.com:8443" }

